FROM docker.elastic.co/logstash/logstash:7.10.0

# RUN rm -f /usr/share/logstash/pipeline/logstash.conf

# COPY config/logstash.yml /usr/share/logstash/config/logstash.yml
# COPY config/pipelines.yml /usr/share/logstash/config/pipelines.yml
# COPY pipeline /usr/share/logstash/pipeline
